"""Rename lvl to level in User model

Revision ID: e13179ab3e1f
Revises: 821b3e9bfbba
Create Date: 2025-11-12 14:12:31.011868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e13179ab3e1f'
down_revision: Union[str, None] = '821b3e9bfbba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=True))
    op.drop_column('users', 'lvl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lvl', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'level')
    # ### end Alembic commands ###
